ALTER TABLE `users`
  ADD COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `users`
  ADD COLUMN `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `users`
  ADD COLUMN `created_by` VARCHAR(255) NOT NULL;

ALTER TABLE `users`
  ADD COLUMN `updated_by` VARCHAR(255);